services:
  nextjs:
    build:
      context: ../..
      args:
        NEXT_PUBLIC_HOST_URL: http://localhost:3000
      dockerfile: Dockerfile
    hostname: nextjs-template
    container_name: nextjs-template
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    env_file: ../../.env
    restart: unless-stopped
    cap_drop: [ALL]
    cap_add: [NET_BIND_SERVICE]
    security_opt: [no-new-privileges:true]
    read_only: true
    volumes:
      - nextjs_logs:/app/log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  nextjs_logs: